alter table public.v2b_ratings alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.v2b_ratings','id'), greatest(coalesce((select max(id) from public.v2b_ratings),0)+1,1), false);
grant usage, select on sequence public.v2b_ratings_id_seq to authenticated;
