-- Editable skate tiers and locations for the staging Skate Manager.
-- Removed options are archived so historical skate records remain untouched.
begin;

create table if not exists public.skate_options (
  id bigint generated by default as identity primary key,
  option_type text not null check (option_type in ('tier', 'location')),
  name text not null check (length(trim(name)) between 1 and 80),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint skate_options_option_type_name_key unique (option_type, name)
);

alter table public.skate_options enable row level security;
revoke all on public.skate_options from anon, public;
grant select, insert, update, delete on public.skate_options to authenticated;
grant usage, select on sequence public.skate_options_id_seq to authenticated;

drop policy if exists staging_authenticated_access on public.skate_options;
create policy staging_authenticated_access
  on public.skate_options
  for all to authenticated
  using (true) with check (true);

insert into public.skate_options (option_type, name, sort_order) values
  ('tier', 'Tier 1', 10),
  ('tier', 'Tier 2', 20),
  ('tier', 'Tier 3', 30),
  ('tier', 'Mixed Skill', 40),
  ('tier', '3v3', 50),
  ('tier', 'Breakfast of Champions', 60),
  ('tier', 'Skills Development', 70),
  ('tier', 'Stick n Puck', 80),
  ('tier', 'Ladies Elite Shinny - McAlpine', 90),
  ('location', 'Broadmoor', 10),
  ('location', 'Callingwood', 20),
  ('location', 'Canadian Athletic Club', 30),
  ('location', 'Castledowns', 40),
  ('location', 'Clareview', 50),
  ('location', 'Confederation', 60),
  ('location', 'Donnan', 70),
  ('location', 'Downtown Community Arena', 80),
  ('location', 'Grand Trunk Arena', 90),
  ('location', 'Kenilworth', 100),
  ('location', 'Kinsmen', 110),
  ('location', 'Londonderry', 120),
  ('location', 'Meadows Recreation Centre', 130),
  ('location', 'Millenium Place', 140),
  ('location', 'Millwoods', 150),
  ('location', 'NAIT', 160),
  ('location', 'Heavy Metal Place', 180),
  ('location', 'Rivercree', 190),
  ('location', 'Silent Ice Center', 200),
  ('location', 'Terwillegar Rink', 210),
  ('location', 'Tipton', 220),
  ('location', 'ZerOne W.E.M.', 230)
on conflict do nothing;

commit;
