alter table public.player_skills_simple alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.player_skills_simple','id'), greatest(coalesce((select max(id) from public.player_skills_simple),0)+1,1), false);
grant usage, select on sequence public.player_skills_simple_id_seq to authenticated;
